languageCode: "en-us"
baseUrl: "https://jcrumb.github.io"
title: "Aardonyx Blog"
theme: "anubis"
paginate: 10
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0
  - identifier: categories
    name: Categories
    title: Categories
    url: /categories/
    weight: 0

params:
  author: "Jay Crumb"
  email: jay@aardonyx.ca
  avatar: "/images/me.png" # used for microformats
  description: ""
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light-without-switcher
  readMore: true
  disableSummary: false
  style: auto
  social:
    - id: github
      name: jcrumb
