languageCode: "en-US"
baseURL: "https://jcrumb.github.io"
title: "Crumbliacci's Blog"
author: "Jay Crumb"
copyright: "Copyright © Jay Crumb"
theme: "anubis"
enableRobotsTXT: true

services:
  googleAnalytics:
    id: "G-PMSMF8C2BN"

params:
  description: ""
  favicon: "images/favicon.png"
  dateFormat: "2006-01-02"
  style: "light-without-switcher"
  mainSections:
    - blog

markup:
  highlight:
    style: friendly
    lineNos: true
    lineNumbersInTable: false
    codeFences: true
